---
title: "Assignment 0: Class Prerequisites"
output:
  html_document:
    number_sections: false
    toc: no
---

**This assignment is optional**

**Purpose**: The purpose of this assignment is to allow you to self-assess whether you have the prerequisite knowledge and skills required for this course and to give you a head start on programming and working with data in R.

**Skills**: After completing these exercises, you should be able to:

 - Know whether or not they have the prerequisite knowledge and skills required for this course.
 - Use RStudio to write basic R commands.
 - Know the distinctions between different R operators and data types, including numeric, string, and logical data.
 - Use **tidyverse** functions to wrangle and manipulate data in R.
 - Use the **ggplot2** library to create plots in R.

**Tasks**:

1. Take this [three-question self-assessment quiz](https://github.com/emse-madd-gwu/2022-Spring/raw/master/other/self-assessment.pdf). It shouldn't take more than 10-20 minutes to complete, and answers can be compared with the [solutions](https://github.com/emse-madd-gwu/2022-Spring/raw/master/other/self-assessment-solutions.pdf). If you have trouble answering these questions, you may find this course challenging and may want to take other courses or review refresher materials on these topics prior to taking this course.

2. We will work in the R programming language throughout the course, but no prior programming experience is required. We will spend the first two weeks going through exercises to get up to speed in R. To get a head start, you can get familiar with R and RStudio by reading the following lessons:

- ["Getting Started"](https://p4a.seas.gwu.edu/2019-Fall/L1.2-getting-started.html): Installing R & RStudio, basic operators, staying organized with RStudio Projects.
- ["Programming Basics"](https://p4a.seas.gwu.edu/2019-Fall/L2-programming-basics.html): Functions, arguments, objects, data types, packages.
- ["Data Frames"](https://p4a.seas.gwu.edu/2019-Fall/L10-da1-data-frames.html): Learn the foundational data structure, basic data manipulation, and how to import data as a data frame.

3. If you haven't already, register for [DataCamp](https://www.datacamp.com/) using your **@gwu.edu** email address. Then complete the entire [Introduction to the Tidyverse](https://www.datacamp.com/courses/introduction-to-the-tidyverse) DataCamp course. You should go through all four lessons in the course.
