---
title: "Practice Questions"
date: December 01, 2021
week: 14
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: false
---

```{r setup, include=FALSE}
# Basic knit settings
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.retina = 3,
  fig.path = "figs/"
)

library(tidyverse)
library(knitr)
library(kableExtra)
library(here)
library(logitr)
library(fastDummies)
```

## Practice Questions 1

Let's say our utility function is:

$$v_j = \beta_1 x_j^{\mathrm{price}} + \beta_2 x_j^{\mathrm{cacao}} + \beta_3 \delta_j^{\mathrm{hershey}} + \beta_4 \delta_j^{\mathrm{lindt}}$$

And we estimate the following coefficients:

<center>
<div style="width:200px">
Parameter | Coefficient
----------|-----------
$\beta_1$ | -0.1
$\beta_2$ | 0.1
$\beta_3$ | -2.0
$\beta_4$ | -0.1
</div>
</center>

What are the expected probabilities of choosing each of these bars using a logit model?

```{r, echo=FALSE}
tibble(
  Attribute = c("Price", "% Cacao", "Brand"),
  `Bar 1` = c("$1.20", "10%", "Hershey"),
  `Bar 2` = c("$1.50", "60%", "Lindt"),
  `Bar 3` = c("$3.00", "80%", "Ghirardelli"),
) %>%
  kable() %>%
  kable_styling(
      bootstrap_options = c("hover", "condensed"),
      full_width = FALSE)
```

```{r}
# Write code here
```





## Practice Questions 2

**Observations** - Height of students (inches):

```{r, echo=FALSE}
x <- c(65, 69, 66, 67, 68, 72, 68, 69, 63, 70)
x
```

a) Let's say we know that the height of students, $\tilde{x}$, in a classroom follows a normal distribution. A professor obtains the above height measurements students in her classroom. What is the log-likelihood that $\tilde{x} \sim \mathcal{N} (68, 4)$? In other words, compute $\ln \mathcal{L} (\mu = 68, \sigma = 4)$.

```{r}
# Write code here
```

b) Compute the log-likelihood function using the same standard deviation $(\sigma = 4)$ but with the following different values for the mean, $\mu: 66, 67, 68, 69, 70$. How do the results compare? Which value for $\mu$ produces the highest log-likelihood?

```{r, fig.height=4, fig.width=6}
# Write code here
```




## Practice Questions 3

Suppose we estimate the following utility model describing preferences for cars:

$$
u_j = \alpha p_j + \beta_1 x_j^{mpg} + \beta_2 x_j^{elec} + \varepsilon_j
$$

The estimated model produces the following results:

Parameter | Coefficient
----------|------------
$\alpha$ | -0.7
$\beta_1$ | 0.1
$\beta_2$ | -0.4

Hessian:

$$
\begin{bmatrix}
-6000 & 50 & 60
\\
50 & -700 & 50
\\
60 & 50 & -300
\end{bmatrix}
$$

Compute a 95% confidence interval around the coefficients using:

a) Standard errors
b) Simulated draws

```{r}
# Write code here
```

a) Solution using standard errors

```{r}
# Write code here
```

b) Solution using simulated draws

```{r}
# Write code here
```
